# Generated by Django 6.0 on 2026-01-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_picture_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='callsign',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
